[package]
edition = "2021"
name = "misc"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
axum = {version = "0.4", optional = true}
env_logger = "0.9"
log = "0.4"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
tokio = {version = "1", features = ["full"]}

[features]
http = ["axum"]
